# use any python version from python 3.
FROM python:3

WORKDIR /app

# Copy the client script into the container
COPY client.py .

# Install Python dependencies
RUN pip install --no-cache-dir requests

ENTRYPOINT ["python", "client.py"]