# Use the official GCC image as a base
FROM gcc:latest

# Install CMake and GTest
RUN apt-get update && apt-get install -y cmake libgtest-dev

# Set a generic and consistent working directory
WORKDIR /usr/src/app

# Copy all project files into the container
COPY . .

# Ensure the data directory is available inside container and can be mounted from host
RUN mkdir -p data && chmod 777 data
VOLUME ["/usr/src/app/data"]

# Clean and Build:
# 1. Remove the 'build' folder (in case local artifacts from Windows/Mac were copied)
# 2. Configure the project (-S specifies source, -B specifies build directory)
# 3. Compile the project
# 4. Run tests
RUN rm -rf build && \
    cmake -S . -B build && \
    cmake --build build && \
    ctest --output-on-failure

RUN ln -s /usr/src/app/build/runTests /usr/local/bin/tests

# Move to the directory where the executable was created
WORKDIR /usr/src/app

# Default command to run the application
ENTRYPOINT ["./build/ProductRecommendation"]